# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d9248f25301a1c979e95164e98a071fb4ac3a1a65e26a2a5f8e72e2f2e9b908558479d672876d005cbf0e8d772541b5bff0b44f65733b2318bcbf8186393b8c

test:
  secret_key_base: 688c960e90a6cf14d89c6fcd51eb4f6a2803ba2c0ecc60205a33e9b9d5a6b9274bc82dc1f3abd004bf48f077ddf625d74f8d97139e9be16aca90e1aa0a0fa4ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
